config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  get 'home/privacy_policy'
  root 'home#index'
  # devise_for :users, controllers: {confirmations: 'confirmations'}
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
}
  # devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin     
      can :manage, :dashboard 
    end
    # if user.supervisor_role?
    #   can :manage, User
    # end

  end
end

  # def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
#   end
# end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  has_many :user
  belongs_to:sub_comment
end

app/models/mark.rb
# frozen_string_literal: true

class Mark < ApplicationRecord
  belongs_to :term
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
    has_many:user
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
    # acts_as_authorization_role
    has_many :user
end

app/models/standard.rb
# frozen_string_literal: true

class Standard < ApplicationRecord
  has_many :user
  belongs_to :teacher_in_charge
end

app/models/sub_comment.rb
# frozen_string_literal: true

class SubComment < ApplicationRecord
  belongs_to :comment
end

app/models/subject.rb
# frozen_string_literal: true

class Subject < ApplicationRecord
  belongs_to :Standard
end

app/models/teacher_in_charge.rb
# frozen_string_literal: true

class TeacherInCharge < ApplicationRecord
  belongs_to :subject
  belongs_to :class
end

app/models/term.rb
# frozen_string_literal: true

class Term < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  belongs_to :roles
  belongs_to :relatiionship
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!

    def after_sign_in_path(resource)
        user_path(resource)
    end
end

app/controllers/confirmations_controller.rb
# frozen_string_literal: true

class Devise::ConfirmationsController < DeviseController
    # GET /resource/confirmation/new
    def new
      self.resource = resource_class.new
    end
  
    # POST /resource/confirmation
    def create
      self.resource = resource_class.send_confirmation_instructions(resource_params)
      yield resource if block_given?
  
      if successfully_sent?(resource)
        respond_with({}, location: after_resending_confirmation_instructions_path_for(resource_name))
      else
        respond_with(resource)
      end
    end
  
    # GET /resource/confirmation?confirmation_token=abcdef
    def show
      self.resource = resource_class.confirm_by_token(params[:confirmation_token])
      yield resource if block_given?
  
      if resource.errors.empty?
        set_flash_message!(:notice, :confirmed)
        respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
      else
        respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
      end
    end
  
    protected
  
      # The path used after resending confirmation instructions.
      def after_resending_confirmation_instructions_path_for(resource_name)
        is_navigational_format? ? new_session_path(resource_name) : '/'
      end
  
      # The path used after confirmation.
      def after_confirmation_path_for(resource_name, resource)
        if signed_in?(resource_name)
          signed_in_root_path(resource)
          root_path
        else
          new_session_path(resource_name)
        end
      end
  
      def translation_scope
        'devise.confirmations'
      end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # POST /users
    # POST /users.json
    def create
      @user = User.new(params[:user])
  
      respond_to do |format|
        if @user.save
          # Tell the UserMailer to send a welcome email after save
          UserMailer.with(user: @user).welcome_email.deliver_later
  
          format.html { redirect_to(@user, notice: 'User was successfully created.') }
          format.json { render json: @user, status: :created, location: @user }
        else
          format.html { render action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
    
  end
  

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/include/_alert.html.erb
# <% if notice.present? %>
# <div class="alert alert-success" role="alert">
#     <%= notice %>
# </div>
#     <p class="notice">
# <% elsif alert.present? %>
#     <div class="alert alert-danger" role="alert">
#         <%= alert %>
#     </div> 
# <% end %>
<% unless flash.empty? %>
   <script type="text/javascript">
      <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
   	 toastr['<%= type %>']('<%= f[1] %>');
   <% end %>
   </script>
<% end %>

app/views/include/_footer.html.erb
  <footer class="footer mt-auto py-3 bg-light">
  <div class="container">
   <div class="col-md-4"></div>
   <div class="col-md-4"></div>
   <div class="col-md-4">
        <%= link_to home_privacy_policy_path,class:"nav-item" do %>
            <i class="fas fa-file-word"></i>Privacy Policy
        <% end %>
  </div>

  </div>
</footer>

app/views/include/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="fas fa-flag"></i>
      My School
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to root_path, class: "nav-link #{'active font-weight-bold' if current_page?(root_path)}" do %>
          <div class="fa fa-home"></div>
          Home
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-user text-white"></i> <b><%= current_user.email %></b></a>
        
            
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdown02">
         
          <%= link_to  destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <div class="fa fa-sign-out-alt"></div>
                  <b>Sign out</b>
          </li>
          <li>
          <%= link_to edit_user_registration_path, class: "dropdown-item #{'active font-weight-bold' if current_page?(edit_user_registration_path)}" do %>
                <div class="fa fa-cog"></div>
                <b>Account settings</b>
                <% end %>
          </li>
      </li>
      <% end %>
      <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active font-weight-bold' if current_page?(new_user_session_path)}" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active font-weight-bold' if current_page?(new_user_registration_path)}" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100" lang="en">
  <head>
    <title>Schoolapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application','data-turbolinks-eval': 'false','data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-mutate-approach="sync"></script>
  </head>
 
  <body class="d-flex flex-column h-100">
  <header>
      <%= render 'include/header' %>
      <%= render 'include/alert' %>

   </header>
   <p></p>
    <%= yield %>
    <%= render 'include/footer' %>

  </body>
</html>